const D=window.PORTAL_DATA;
const periods=D.period_order||['1day','10days','15days','30days','60days'];
let selected=D.games.slice(0,4).map(g=>g.title.trim());
let current=(D.games[0]?.title||'').trim();
const $=id=>document.getElementById(id);
const row=(title,period)=>D.kpi.find(r=>r.title.trim()===title.trim()&&r.period===period);
const rows=period=>D.kpi.filter(r=>r.period===period);
const gameRows=title=>D.kpi.filter(r=>r.title.trim()===title.trim()).sort((a,b)=>periods.indexOf(a.period)-periods.indexOf(b.period));
function money(v){if(v==null||isNaN(v))return'-';v=Number(v);if(Math.abs(v)>=1e6)return'$'+(v/1e6).toFixed(2)+'M';if(Math.abs(v)>=1e3)return'$'+(v/1e3).toFixed(1)+'K';return'$'+v.toLocaleString(undefined,{maximumFractionDigits:0});}
function num(v){if(v==null||isNaN(v))return'-';v=Number(v);if(Math.abs(v)>=1e6)return(v/1e6).toFixed(1)+'M';if(Math.abs(v)>=1e3)return(v/1e3).toFixed(1)+'K';return Math.round(v).toLocaleString();}
function pct(v){if(v==null||isNaN(v))return'-';return (Number(v)*100).toFixed(1)+'%'}
function fmt(v,m){if(m.includes('usd')||m==='revenue_usd')return money(v);if(m==='pur'||m.includes('share')||m.includes('ratio'))return pct(v);return num(v)}
const labels={revenue_usd:'Revenue',dau:'DAU',dnu:'DNU',pu:'PU',pur:'PUR',arpu_usd:'ARPU',arppu_usd:'ARPPU'};
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));if(id==='dashboard')renderDashboard();if(id==='library')renderLibrary();if(id==='detail')renderDetail(current);if(id==='compare')renderCompare();if(id==='ranking')renderRanking();if(id==='retention')renderRetention();scrollTo(0,0)}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>showView(b.dataset.view));
function launchYear(g){return g.launch_date?String(new Date(g.launch_date).getFullYear()):'Unknown'}
function region(g){return g.region||'Global'}
function d30(title){return row(title,'30days')||gameRows(title).at(-1)||{}}
function d1(title){return row(title,'1day')||gameRows(title)[0]||{}}
function renderDashboard(){
 $('currencyNote').textContent=`프로토타입 환산 기준: 1 USD = ${D.currency_standard.prototype_usd_rate.toLocaleString()} KRW`;
 const games=D.games, years=games.map(launchYear).filter(y=>y!=='Unknown');
 const topRev=[...games].sort((a,b)=>(d30(b.title).revenue_usd||0)-(d30(a.title).revenue_usd||0))[0];
 const topDau=[...games].sort((a,b)=>(d1(b.title).dau||0)-(d1(a.title).dau||0))[0];
 $('summaryCards').innerHTML=[['Games',games.length,'비교 가능한 게임'],['Regions',new Set(games.map(g=>region(g))).size,'서비스 지역'],['Top D+30 Revenue',topRev?topRev.title:'-',topRev?money(d30(topRev.title).revenue_usd):''],['Top D+1 DAU',topDau?topDau.title:'-',topDau?num(d1(topDau.title).dau):'']].map(c=>`<div class="card"><span>${c[0]}</span><strong>${c[1]}</strong><small>${c[2]||''}</small></div>`).join('');
 renderBars('dashBars',rows('30days'),$('dashMetric').value);renderPills('quickCompare',D.games.map(g=>g.title),selected,true);$('homeGames').innerHTML=D.games.slice(0,6).map(gameCard).join('')
}
function renderBars(id,data,metric){const arr=[...data].filter(r=>r[metric]!=null&&!isNaN(r[metric])).sort((a,b)=>b[metric]-a[metric]).slice(0,8);const max=Math.max(...arr.map(r=>Number(r[metric])),1);$(id).innerHTML=arr.map((r,i)=>`<div class="bar-row"><div class="rank">${i+1}</div><div><div class="bar-title">${r.title.trim()}</div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(4,r[metric]/max*100)}%"></div></div></div><div class="bar-value">${fmt(r[metric],metric)}</div></div>`).join('')}
function renderPills(id,items,active,multi){$(id).innerHTML=items.map(t=>`<button class="pill ${active.includes(t.trim())?'active':''}" data-title="${t.trim()}">${t.trim()}</button>`).join('');$(id).querySelectorAll('.pill').forEach(p=>p.onclick=()=>{const t=p.dataset.title;if(multi){selected=selected.includes(t)?selected.filter(x=>x!==t):([...selected,t].slice(0,5));renderDashboard();renderCompare();}else{current=t;renderDetail(t);showView('detail')}})}
function goCompare(){showView('compare')}
function gameCard(g){const r=d30(g.title), r1=d1(g.title);return`<div class="game-card" onclick="current='${g.title}';showView('detail')"><h3>${g.title}</h3><div class="meta"><span class="tag">${region(g)}</span><span class="tag">${launchYear(g)}</span><span class="tag">Score ${g.score}</span></div><div class="score">${g.score}<small>/100</small></div><div class="metric-line"><div class="metric"><span>D+30 Revenue</span><b>${money(r.revenue_usd)}</b></div><div class="metric"><span>D+1 DAU</span><b>${num(r1.dau)}</b></div><div class="metric"><span>D+30 PUR</span><b>${pct(r.pur)}</b></div><div class="metric"><span>Retention</span><b>Required</b></div></div></div>`}
function fillFilters(){const regions=[...new Set(D.games.map(g=>region(g)))].sort();const years=[...new Set(D.games.map(launchYear))].sort().reverse();[['libRegion',regions,'ALL Region'],['libYear',years,'ALL Year']].forEach(([id,arr,label])=>{$(id).innerHTML=`<option value="">${label}</option>`+arr.map(x=>`<option>${x}</option>`).join('')})}
function renderLibrary(){let q=($('libSearch').value||'').toLowerCase(), rg=$('libRegion').value, yr=$('libYear').value, sort=$('libSort').value;let list=D.games.filter(g=>(!q||g.title.toLowerCase().includes(q))&&(!rg||region(g)===rg)&&(!yr||launchYear(g)===yr));list.sort((a,b)=>{if(sort==='score')return b.score-a.score;if(sort==='dau')return(d1(b.title).dau||0)-(d1(a.title).dau||0);return(d30(b.title)[sort]||0)-(d30(a.title)[sort]||0)});$('libraryGrid').innerHTML=list.map(gameCard).join('')||'<div class="empty">검색 결과가 없습니다.</div>'}
function renderDetail(title){current=title||current;const g=D.games.find(x=>x.title.trim()===current.trim())||D.games[0];const rs=gameRows(g.title);const r30=d30(g.title), r1=d1(g.title);const channels=['google','apple','mycard','razer','unipin','oneone','ebanx','xsolla'].map(k=>[k,(r30[k+'_usd']||0)]).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]);$('detailBody').innerHTML=`<div class="detail-hero"><section class="panel detail-title"><p class="eyebrow">Game Detail</p><h2>${g.title}</h2><div class="meta"><span class="tag">${region(g)}</span><span class="tag">Launch ${launchYear(g)}</span><span class="tag">${g.periods.join(' · ')}</span></div><p>이 화면은 KPI 숫자와 함께 런칭 당시 성공 요인, 이슈, Lessons Learned를 남기는 지식 카드입니다.</p></section><section class="panel"><p class="eyebrow">Launch Score</p><div class="score">${g.score}<small>/100</small></div><div class="metric-line"><div class="metric"><span>D+30 Revenue</span><b>${money(r30.revenue_usd)}</b></div><div class="metric"><span>D+1 DAU</span><b>${num(r1.dau)}</b></div><div class="metric"><span>D+30 ARPPU</span><b>${money(r30.arppu_usd)}</b></div><div class="metric"><span>D+30 PUR</span><b>${pct(r30.pur)}</b></div></div></section></div><div class="grid two"><section class="panel"><div class="panel-head"><div><p class="eyebrow">KPI Curve</p><h3>Revenue / DAU / PUR</h3></div></div>${detailTable(rs)}</section><section class="panel"><p class="eyebrow">Retention</p><h3>Data Required</h3><div class="empty">업로드된 1M Retention 시트에 실제 값이 없어 표시할 수 없습니다.<br/>정식 운영 데이터에는 D1 / D3 / D7 / D14 / D30을 표준으로 추가합니다.</div></section></div><div class="grid two"><section class="panel"><p class="eyebrow">Revenue Composition</p><h3>D+30 Channel Mix</h3>${channels.length?channels.map(([k,v])=>`<div class="bar-row"><div></div><div><div class="bar-title">${k.toUpperCase()}</div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(4,v/Math.max(...channels.map(c=>c[1]))*100)}%"></div></div></div><div>${money(v)}</div></div>`).join(''):'<div class="empty">채널 데이터 없음</div>'}</section><section class="panel"><p class="eyebrow">Lessons Learned</p><h3>사업부 기록 영역</h3><ul><li>Success Factors: 런칭 성공 요인 기록</li><li>Risk / Issue: 서버, 마케팅, 결제 이슈 기록</li><li>Next Launch Memo: 다음 신작에 반영할 내용 기록</li></ul></section></div>`}
function detailTable(rs){return`<div class="table-wrap"><table><thead><tr><th>Period</th><th>Revenue</th><th>DAU</th><th>PU</th><th>PUR</th><th>ARPU</th><th>ARPPU</th></tr></thead><tbody>${rs.map(r=>`<tr><td>${r.period}</td><td>${money(r.revenue_usd)}</td><td>${num(r.dau)}</td><td>${num(r.pu)}</td><td>${pct(r.pur)}</td><td>${money(r.arpu_usd)}</td><td>${money(r.arppu_usd)}</td></tr>`).join('')}</tbody></table></div>`}
function renderCompare(){renderPills('comparePick',D.games.map(g=>g.title),selected,true);const m=$('compareMetric').value;const max=Math.max(...selected.flatMap(t=>gameRows(t).map(r=>r[m]||0)),1);$('lineChart').innerHTML=selected.map(t=>`<div class="line-group" title="${t}">${periods.map(p=>{let v=(row(t,p)||{})[m]||0;return`<div class="line-bar" style="height:${Math.max(2,v/max*100)}%"></div>`}).join('')}</div>`).join('');$('compareTable').innerHTML=`<thead><tr><th>Game</th>${periods.map(p=>`<th>${p}</th>`).join('')}</tr></thead><tbody>${selected.map(t=>`<tr><td><b>${t}</b></td>${periods.map(p=>`<td>${fmt((row(t,p)||{})[m],m)}</td>`).join('')}</tr>`).join('')}</tbody>`}
function renderRanking(){const p=$('rankPeriod').value,m=$('rankMetric').value;const arr=rows(p).filter(r=>r[m]!=null&&!isNaN(r[m])).sort((a,b)=>b[m]-a[m]);$('rankTable').innerHTML=`<thead><tr><th>#</th><th>Game</th><th>Period</th><th>${labels[m]||m}</th><th>DAU</th><th>PUR</th><th>ARPPU</th></tr></thead><tbody>${arr.map((r,i)=>`<tr><td>${i+1}</td><td><b>${r.title.trim()}</b></td><td>${r.period}</td><td>${fmt(r[m],m)}</td><td>${num(r.dau)}</td><td>${pct(r.pur)}</td><td>${money(r.arppu_usd)}</td></tr>`).join('')}</tbody>`}
function renderRetention(){$('retentionTable').innerHTML=`<thead><tr><th>Game</th><th>D1</th><th>D3</th><th>D7</th><th>D14</th><th>D30</th><th>Status</th></tr></thead><tbody>${D.retention.map(r=>`<tr><td><b>${r.title}</b></td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td><td><span class="warn">Data Required</span></td></tr>`).join('')}</tbody>`}
['dashMetric','compareMetric','rankPeriod','rankMetric'].forEach(id=>$(id).addEventListener('change',()=>{renderDashboard();renderCompare();renderRanking()}));['libSearch','libRegion','libYear','libSort'].forEach(id=>$(id).addEventListener('input',renderLibrary));$('globalSearch').addEventListener('input',e=>{$('libSearch').value=e.target.value;showView('library')});fillFilters();renderDashboard();
